### PR TITLE
Moved TS related packages to devDependencies

### PR DESCRIPTION
**Pull request by harixth**
**What has Changed?**
Excluding typescript related packages to reduce down package size so that it does not get bloated.

**Impacts**
The bundle size for this package should be significantly reduced when installing in other projects.

### CODE REVIEW

**Comment by arminrosu** [comment]
@cb-navaneedhan @cb-seenivasan can you folks merge this?

**Comment by luads** [comment]
This is very much needed. Your package is currently at `54mb`. @cb-goutham any chance you can address it?

**Comment by cb-rakesh** [comment]
This has been merged in v2.2.0

**Comment by arminrosu** [comment]
@cb-rakesh you forgot to move `"typescript": "^3.9.3"` to devDeps as well. That's the biggest dependency. Issue still not resolved.

**Comment by lohiaad** [comment]
@cb-rakesh issue not closed yet. need to move "typescript": "^3.9.3" to devDependencies.

**Comment by arminrosu** [comment]
Now it seems to be fine. Finally. Thanks @cb-khushbubibay

**Pull request closed without merging**
